config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :users
  resources :shops do
    resources :products, only: [:show, :index, :new, :create]
  end
  resources :products, only: [:destroy, :edit, :update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'products,to:products#index', as: :show_product
  #get 'products/: id, to:product#show',as: :products
  
end
#new_shop_product GET    /shops/:shop_id/products/new(.:format)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_float: true }
  validates :amount, presence: true, numericality: { only_integer: true } # preguntar
  has_one_attached :image
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :name, presence: true, uniqueness: true
  validates :history, presence: true
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shops

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  #validates :phone, presence: true, uniqueness: true
  #validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_shop, only: [:new, :create]
    def index
        if params[:query].present?
          @products = Product.where("lower(title)  LIKE ?", "%" + params[:query].downcase + "%")
        else
          @products = Product.all
        end
      end
    
    def show
     @product = Product.find(params[:id])
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(product_params)
        @product.shop = @shop
        if @product.save
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      redirect_to root_path
    end



    def destroy
      @product = Product.find(params[:id])
       @product.destroy
       redirect_to root_path
    end


    private

    def set_shop
    @shop = Shop.find(params[:shop_id])
    end

    def product_params
        params.require(:product).permit(:title, :description, :price, :amount, :image)
    end
    
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    if params[:query].present?
      @query = params[:query]
      @shops = Shop.where("name LIKE ?","%#{params[:query]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @shops = Shop.all
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @user = current_user
    @product = Product.new(shop: @shop)
    #@user = User.new(shop: @shop)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id
    if @shop.save
      redirect_to shops_path(@shop)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @shop.update(shop_params)
    redirect_to shop_path(@shop)
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :history, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>La Canasta Verde</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="alert"><%= alert %></p>
    <div>
      <%= yield %>
    </div>
     <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p><%= current_user.try(:email) %></p>
<p>Hola, <%= current_user.try(:first_name) %></p>
<% if user_signed_in? %>
<p> 'usuario logueado'</p>
<% else %> 
<p> 'usuario no logueado'
<% end %> </p>
 </div>

app/views/products/edit.html.erb
<div class="container mt-3">
  <h1 class="text-center"> Editar Producto</h1>
<div class="container">
 <div class="border p-5 mt-2" >
  <%= simple_form_for @product do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :amount %>
    <%= f.input :price %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Subir producto", class:"btn btn-add" %>
  <% end %>
</div>
</div>
</div>

app/views/products/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dltcgy0em/image/upload/v1629777435/sharon-pittaway-KUZnfk-2DSQ-unsplash_rhdxfk.jpg);">
  <div class="container">
    <h1>La Canasta verde <strong></strong> <strong></strong>!</h1>
    <p>Vegetales desde la huerta directamente a su mesa.</p>    
  </div>
</div>
</div>
<div class="container mt-5">
<div class="text-center">
  <h2 class="text-center">Productos</h2>
</div>
<div class="container mt-5">
    <div class="d-flex flex-wrap justify-content-around">
    <% @products.each do |product| %>    
      <div class="card-trip m-2">
          <% if product.image.attached? %>
            <%= cl_image_tag product.image.key, height: 800, width: 1000, crop: :fill %>
            <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to product.title.capitalize, shop_product_path(product.shop, product), class:"text-decoration-none" %></h2>
            <p class="card-trip-pricing">Precio: $<%= product.price %></p>
          </div>
          <div class="mt-2">
            <p class="card-amount">Cantidad: <%= product.amount %></p>
            <p class="card-amount">shop: <%= product.shop.name.capitalize %></p>            
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/products/new.html.erb
<div class="container mt-3">
  <h1 class="text-center"> Crear Producto</h1>
<div class="container">
 <div class="border p-5 mt-2" >
  <%= simple_form_for([@shop, @product]) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :amount %>
    <%= f.input :price %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Subir producto", class:"btn btn-add" %>
  <% end %>
</div>
</div>
</div>

app/views/products/show.html.erb
<!--<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><p><%= link_to  @product.shop.name.capitalize, shop_path(@product.shop) %> </p></h1>
        <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.phone %></h5>
        <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.address %></h5>
        <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.email %></h5>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>-->
<!--<div class="container mb-2 cont-product p-2">-->
<br /><br /><br /><br /><br /><br />
<div class="d-flex justify-content-center align-text-center align-self-center aling-item-center" role="group">
  <%# container info product %>
    <%# product %>
    <div class="product-card col-3 text-center">
      <h2><%= @product.title.try(:capitalize) %></h2>
      <% if @product.image.attached? %>
        <%= cl_image_tag @product.image.key, height:250, width:250, crop: :fill , class: "img-thumbnail rounded-circle my-avatar" %>
      <% end %><br /><br />
      <!-- Button trigger modal -->
      <button class="btn btn-contact" data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-envelope"></i> Contacto</button>
      <br /><br />
    </div>
    <%# description %>
    <div class="product-card col-6 text-center">
      <h3>Descripción</h3>
      <p><%= @product.description.capitalize %></p>
      <h4><%=@product.price%></h4>
      <p><%= link_to  @product.shop.name.capitalize, shop_path(@product.shop), class:"text-decoration-none" %> </p>
    </div>
</div>




<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4> Nos puedes llamar o escribir.</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
        <div class="form-group">
          <label for="recipient-name" class="col-form-label">Telefono:</label>
          <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.phone %></h5>
        </div>
        <div class="form-group">
          <label for="message-text" class="col-form-label">Email:</label>
          <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.email %></h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<
  </h1><div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dltcgy0em/image/upload/v1629667977/Verduras_6_tzolbf.jpg);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

<!--<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

app/views/shared/_carousel-html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide mb-5" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dltcgy0em/image/upload/v1629777409/inge-poelman-83fP8jc5m9s-unsplash_lxiuqf.jpg" class="d-block w-100 rounded" alt="flat image">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dltcgy0em/image/upload/v1629778093/pexels-alejandro-barr%C3%B3n-96715_xnptzl.jpg" class="d-block w-100 rounded" alt="flat image">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dltcgy0em/image/upload/v1629777541/markus-spiske-4yK8iDaWnm8-unsplash_vifm9c.jpg" class="d-block w-100 rounded" alt="flat image">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!--<div class= "container-fluid">-->
  
    
<footer class="mt-4 text-center">
  <div class="text-center footer-links mb-4">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
    <p>contacto@lacanastaverde.com
    Tel: 555-5555555</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "#", class: "navbar-brand verde" do %> 
    <%= image_tag "Vegetales2.jpg", crop: :fill, class:"nav-logo" %> La Canasta verde
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="" role="group">
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
      <div class="container">
	      <div class="row">
          <div class="col-xs-10 col-xs-offset-1 justify-content-center">
            <div class="input-group">
              <input class="form-control" placeholder="Busca lo que quieres" name="query" id="search_query" type="text">
              <div class="input-group-btn">
                <button name="button" type="submit" class="btn btn-search">
                  <i class="fas fa-search icon"></i>
                </button>
              </div>
            </div>
          </div>
	      </div>
      </div>
    <% end %>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Inicio", root_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Tiendas', shops_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mensajes", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag "xhgkai3ga6694q799it0584caf3r", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Crear Tienda", new_shop_path, class: "dropdown-item" %>
            <%= link_to "Mi tienda", "#", class: "dropdown-item" %>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>  
      <% end %>
    </ul>
  </div>
</div>

app/views/shops/_form.html.erb
<%= form_for(shop) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.text_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :history %>
    <%= f.text_field :history, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit shop</h1>
        <div class="mt-3">
          <%= render "form", shop: @shop %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="container mt-2">
  <head>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="row">
      <div class="col-12 text-center">
        <h2>Descubre una selección de tiendas</h2>
        <div class="row">
          <div class="col">
            <% if @query %>
              <p>You searched for <strong><%= @query %></strong>. We found <%= @shops.count %> shops out of our <%= Shop.count %> on our website.</p>
            <% else %>
              <p>Tiendas disponibles:<%= Shop.count %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div> 
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/release/v5.0.10/css/all.css">
    <link rel="stylesheet" href="css/style.css"> -->
  </head> 
  <div>  
    <div class="d-flex flex-wrap justify-content-around">
        <% @shops.each do |shop| %>
          <div class="card-shop m-4" style="width: 18rem;">
            <% if shop.image.attached? %>
                 <%= cl_image_tag shop.image.key, height: 300, width: 400, crop: :fill %>
               <% end %>
            <div class="card-shop-infos">
              <h2><strong><%= link_to shop.name.capitalize, shop_path(shop), class:"text-decoration-none" %></strong></h2>
            </div>
          </div>    
        <% end %>
      </div>  
    </div>
  </div>  
</div>

app/views/shops/new.html.erb
<div class="container mt-5">
<h1 class="text-center"> Crear Tienda</h1>
  <div class="border p-5 mt-2" >
  <%= simple_form_for [ @shop ] do |f| %>
    <%= f.input :name %>
    <%= f.input :history %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Subir tienda", class:"btn btn-add" %>
  <% end %>
</div>
</div>

app/views/shops/show.html.erb
<div>
  <%= render 'shared/carousel' %>
</div>

<%# container info shop %>
<div class="d-flex justify-content-center" role="group">
  <%# usuario %>
  <div class="col-3 text-center "><h2><%= @shop.name.capitalize %></h2><br />
  <% if @shop.image.attached? %>
    <%= cl_image_tag(@shop.image.key, height:250, width:250, crop: :fill,class: "img-thumbnail rounded-circle my-avatar")%>
  <% else %>
    <img src="https://i.imgur.com/WyxbTOS.png" class="img-thumbnail" alt="Servicio">
  <% end %>

   <!-- <img src="https://www.hola.com/imagenes/decoracion/20210408187392/plantar-huerto-urbano-primavera-mc/0-938-406/plantar-huerto-primavera-m.jpg
" class="img-thumbnail rounded-circle my-avatar" alt="..."><br />
    <br /> -->
     <!-- Button trigger modal -->
    <button class="btn btn-contact" data-toggle="modal" data-target="#exampleModalCenter"><i class="fas fa-envelope"></i> Contacto</button>
  </div>
  <%# historia %>
  <div class="col-6 text-center">
    <h2>Historia</h2>
    <p><%= @shop.history.capitalize %></p>
  </div>
</div>

<div class="container mb-5 pt-5">
  <div class="container">
    <ul>
      <h3 class="text-center">Productos</h3>
      <div class="d-flex flex-wrap justify-content-around">
        <% @shop.products.each do |product| %>

          <div class="card-trip m-4">
            <% if product.image.attached? %>
              <%= cl_image_tag product.image.key, height: 300, width: 400, crop: :fill %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= link_to product.title.capitalize, shop_product_path(product.shop, product), class:"text-decoration-none" %></h2>
                <p class="card-price">Precio: $ <%= product.price %></p>
              </div>
              <div class="mt-2">
                <p class="card-amount">Cantidad: <%= product.amount %></p>
              </div>
              <div>
                <!--<a class="fas fa-pen text-decoration-none" href="edit_product_path(product)">-->
                <%= link_to "Editar", edit_product_path(product), class:"btn btn-primary btn-sm" %>
                <%= link_to "Eliminar", product_path(product), method: :delete, class:"btn btn-primary btn-sm" %>
                <!--<a class="fas fa-trash-alt text-decoration-none" href="product_path(product)", method: :delete>-->
              </div>
            </div>
          </div>
        <% end %> 
      </div>
      <%= link_to "+ Agregar producto", new_shop_product_path(@shop), class: "btn btn-add" %> 
    </ul>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4> Nos puedes llamar o escribir.</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
        <div class="form-group">
          <label for="recipient-name" class="col-form-label">Telefono:</label>
          <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.phone %></h5>
        </div>
        <div class="form-group">
          <label for="message-text" class="col-form-label">Email:</label>
          <h5 class="modal-title" id="exampleModalLongTitle"><%= @product.shop.user.email %></h5>
        </div>
      </div>
    </div>
  </div>
</div>